export const shopData = [
  {
    //Make the item hover show the name "Heart Palpitations", move it show its shows "Rank 0, Rank 1, etc.."
    itemName: "Heart Palpitation",
    infectability: 0,
    spreadClickPerSecond: 0,
    growthFactor: 2,
    growClickPerSecond: 0,
    income: 1,
    price: 250,
    initialPrice: 250,
    divider: true,
    src: "./Images/ShopItems/ShopItem1.png",
    upgradeSrc1: "./Images/ShopItems/ShopItem1Upgrade1.png",
    upgradeSrc2: "./Images/ShopItems/ShopItem1Upgrade2.png",
    upgradeSrc3: "./Images/ShopItems/ShopItem1Upgrade3.png",
    alt: "aaa",
    amount: 0,
    id: 0,
    index: 0,
    price10: 0,
    price100: 0,
    price1000: 0,
    itemUnlocked: true,
    levelToUnlock: 1,
    upgrades: 0,
    displayUpgrade: false,
    upgradeStats: [
      {
        infectability: 8,
        spreadClickPerSecond: 8,
        growthFactor: 8,
        growClickPerSecond: 8,
        income: 8,
        price: 1000000,
      },
      {
        infectability: 9,
        spreadClickPerSecond: 9,
        growthFactor: 9,
        growClickPerSecond: 9,
        income: 9,
        price: 1000000,
      },
      {
        infectability: 10,
        spreadClickPerSecond: 10,
        growthFactor: 10,
        growClickPerSecond: 10,
        income: 10,
        price: 1000000,
      },
      {
        infectability: 0,
        spreadClickPerSecond: 0,
        growthFactor: 0,
        growClickPerSecond: 0,
        income: 0,
        price: 1000000,
      },
    ],
  },
  {
    itemName: "Lungs",
    infectability: 0,
    spreadClickPerSecond: 0,
    growthFactor: 0,
    growClickPerSecond: 0,
    income: 5,
    price: 250,
    initialPrice: 250,
    divider: true,
    src: "./Images/ShopItems/ShopItem2.png",
    upgradeSrc1: "./Images/ShopItems/ShopItem2Upgrade1.png",
    upgradeSrc2: "./Images/ShopItems/ShopItem2Upgrade2.png",
    upgradeSrc3: "./Images/ShopItems/ShopItem2Upgrade3.png",
    alt: "aaa",
    amount: 0,
    id: 1,
    index: 1,
    price10: 0,
    price100: 0,
    price1000: 0,
    itemUnlocked: true,
    levelToUnlock: 1,
    upgrades: 0,
    displayUpgrade: false,
    upgradeStats: [
      {
        infectability: 8,
        spreadClickPerSecond: 8,
        growthFactor: 8,
        growClickPerSecond: 8,
        income: 8,
        price: 1000000,
      },
      {
        infectability: 9,
        spreadClickPerSecond: 9,
        growthFactor: 9,
        growClickPerSecond: 9,
        income: 9,
        price: 1000000,
      },
      {
        infectability: 10,
        spreadClickPerSecond: 10,
        growthFactor: 10,
        growClickPerSecond: 10,
        income: 10,
        price: 1000000,
      },
      {
        infectability: 0,
        spreadClickPerSecond: 0,
        growthFactor: 0,
        growClickPerSecond: 0,
        income: 0,
        price: 1000000,
      },
    ],
  },
  {
    itemName: "Livers",
    infectability: 10,
    spreadClickPerSecond: 0,
    growthFactor: 0,
    growClickPerSecond: 0,
    income: 3,
    price: 250,
    initialPrice: 250,
    divider: true,
    src: "./Images/ShopItems/ShopItem3.png",
    upgradeSrc1: "./Images/ShopItems/ShopItem3Upgrade1.png",
    upgradeSrc2: "./Images/ShopItems/ShopItem3Upgrade2.png",
    upgradeSrc3: "./Images/ShopItems/ShopItem3Upgrade3.png",
    alt: "aaa",
    amount: 0,
    id: 2,
    index: 2,
    price10: 0,
    price100: 0,
    price1000: 0,
    itemUnlocked: true,
    levelToUnlock: 1,
    upgrades: 0,
    displayUpgrade: false,
    upgradeStats: [
      {
        infectability: 8,
        spreadClickPerSecond: 8,
        growthFactor: 8,
        growClickPerSecond: 8,
        income: 8,
        price: 1000000,
      },
      {
        infectability: 9,
        spreadClickPerSecond: 9,
        growthFactor: 9,
        growClickPerSecond: 9,
        income: 9,
        price: 1000000,
      },
      {
        infectability: 10,
        spreadClickPerSecond: 10,
        growthFactor: 10,
        growClickPerSecond: 10,
        income: 10,
        price: 1000000,
      },
      {
        infectability: 0,
        spreadClickPerSecond: 0,
        growthFactor: 0,
        growClickPerSecond: 0,
        income: 0,
        price: 1000000,
      },
    ],
  },
  {
    itemName: "Ovaries",
    infectability: 0,
    spreadClickPerSecond: 0,
    growthFactor: 0,
    growClickPerSecond: 1,
    income: 0,
    price: 750,
    initialPrice: 750,
    divider: true,
    src: "./Images/ShopItems/ShopItem4.png",
    upgradeSrc1: "./Images/ShopItems/ShopItem4Upgrade1.png",
    upgradeSrc2: "./Images/ShopItems/ShopItem4Upgrade2.png",
    upgradeSrc3: "./Images/ShopItems/ShopItem4Upgrade3.png",
    alt: "aaa",
    amount: 0,
    id: 3,
    index: 3,
    price10: 0,
    price100: 0,
    price1000: 0,
    itemUnlocked: false,
    levelToUnlock: 2,
    upgrades: 0,
    displayUpgrade: false,
    upgradeStats: [
      {
        infectability: 8,
        spreadClickPerSecond: 8,
        growthFactor: 8,
        growClickPerSecond: 8,
        income: 8,
        price: 1000000,
      },
      {
        infectability: 9,
        spreadClickPerSecond: 9,
        growthFactor: 9,
        growClickPerSecond: 9,
        income: 9,
        price: 1000000,
      },
      {
        infectability: 10,
        spreadClickPerSecond: 10,
        growthFactor: 10,
        growClickPerSecond: 10,
        income: 10,
        price: 1000000,
      },
      {
        infectability: 0,
        spreadClickPerSecond: 0,
        growthFactor: 0,
        growClickPerSecond: 0,
        income: 0,
        price: 1000000,
      },
    ],
  },
  {
    itemName: "Teeth",
    infectability: 0,
    spreadClickPerSecond: 0,
    growthFactor: 10,
    growClickPerSecond: 0,
    income: 0,
    price: 750,
    initialPrice: 750,
    divider: true,
    src: "./Images/ShopItems/ShopItem5.png",
    upgradeSrc1: "./Images/ShopItems/ShopItem5Upgrade1.png",
    upgradeSrc2: "./Images/ShopItems/ShopItem5Upgrade2.png",
    upgradeSrc3: "./Images/ShopItems/ShopItem5Upgrade3.png",
    alt: "aaa",
    amount: 0,
    id: 4,
    index: 4,
    price10: 0,
    price100: 0,
    price1000: 0,
    itemUnlocked: false,
    levelToUnlock: 2,
    upgrades: 0,
    displayUpgrade: false,
    upgradeStats: [
      {
        infectability: 8,
        spreadClickPerSecond: 8,
        growthFactor: 8,
        growClickPerSecond: 8,
        income: 8,
        price: 1000000,
      },
      {
        infectability: 9,
        spreadClickPerSecond: 9,
        growthFactor: 9,
        growClickPerSecond: 9,
        income: 9,
        price: 1000000,
      },
      {
        infectability: 10,
        spreadClickPerSecond: 10,
        growthFactor: 10,
        growClickPerSecond: 10,
        income: 10,
        price: 1000000,
      },
      {
        infectability: 0,
        spreadClickPerSecond: 0,
        growthFactor: 0,
        growClickPerSecond: 0,
        income: 0,
        price: 1000000,
      },
    ],
  },
  {
    itemName: "Teeth",
    infectability: 0,
    spreadClickPerSecond: 0,
    growthFactor: 0,
    growClickPerSecond: 0,
    income: 0,
    price: 100,
    initialPrice: 100,
    divider: false,
    src: "./Images/ShopItems/ShopItem6.png",
    upgradeSrc1: "./Images/ShopItems/ShopItem6Upgrade1.png",
    upgradeSrc2: "./Images/ShopItems/ShopItem6Upgrade2.png",
    upgradeSrc3: "./Images/ShopItems/ShopItem6Upgrade3.png",
    alt: "aaa",
    amount: 0,
    id: 5,
    index: 5,
    price10: 0,
    price100: 0,
    price1000: 0,
    itemUnlocked: false,
    levelToUnlock: 3,
    upgrades: 0,
    displayUpgrade: false,
    upgradeStats: [
      {
        infectability: 8,
        spreadClickPerSecond: 8,
        growthFactor: 8,
        growClickPerSecond: 8,
        income: 8,
        price: 1000000,
      },
      {
        infectability: 9,
        spreadClickPerSecond: 9,
        growthFactor: 9,
        growClickPerSecond: 9,
        income: 9,
        price: 1000000,
      },
      {
        infectability: 10,
        spreadClickPerSecond: 10,
        growthFactor: 10,
        growClickPerSecond: 10,
        income: 10,
        price: 1000000,
      },
      {
        infectability: 0,
        spreadClickPerSecond: 0,
        growthFactor: 0,
        growClickPerSecond: 0,
        income: 0,
        price: 1000000,
      },
    ],
  },
];
