export const spellData = [
  {
    spellName: "Smite",
    src: "./Images/Spells/edited-1.png",
    alt: "aaa",
    index: 0,
    spellUnlocked: true,
    levelToUnlock: 1,
    spellDamage: 0,
    cooldown: 60,
    cooldownTimer: 60,
    onCooldown: true,
    toolTipDescription1: "Deal ",
    toolTipDescription2:
      " damage Instantly. Damage Scales with level and experience.",
    toolTipDescription3: "Kills with this spell grant +20% gold.",
  },
  {
    spellName: "Smite",
    src: "./Images/Spells/edited-2.png",
    alt: "aaa",
    index: 1,
    spellUnlocked: true,
    levelToUnlock: 1,
    spellDamage: "",
    cooldown: 120,
    cooldownTimer: 0,
    onCooldown: true,
    toolTipDescription1: "+100% chime gathering for 10 seconds.",
    toolTipDescription2: "",
    toolTipDescription3: "",
  },
  {
    spellName: "Smite",
    src: "./Images/Spells/edited-3.png",
    alt: "aaa",
    index: 2,
    spellUnlocked: true,
    levelToUnlock: 1,
    spellDamage: "",
    cooldown: 120,
    cooldownTimer: 0,
    onCooldown: false,
    toolTipDescription1: "5x chimes per click for 7 seconds.",
    toolTipDescription2: "",
    toolTipDescription3: "",
  },
  {
    spellName: "Smite",
    src: "./Images/Spells/edited-4.png",
    alt: "aaa",
    index: 3,
    spellUnlocked: true,
    levelToUnlock: 1,
    spellDamage: 111,
    cooldown: 180,
    cooldownTimer: 0,
    onCooldown: false,
    toolTipDescription1: "Increase your current meeps by 10% ",
    toolTipDescription2: "",
    toolTipDescription3: "",
  },
  {
    spellName: "Smite",
    src: "./Images/Spells/edited-5.png",
    alt: "aaa",
    index: 4,
    spellUnlocked: true,
    levelToUnlock: 1,
    spellDamage: "",
    cooldown: 300,
    cooldownTimer: 0,
    onCooldown: false,
    toolTipDescription1: "Reset Cooldowns of all spells.",
    toolTipDescription2: "",
    toolTipDescription3: "",
  },
  {
    spellName: "Smite",
    src: "./Images/Spells/edited-6.png",
    alt: "aaa",
    index: 5,
    spellUnlocked: true,
    levelToUnlock: 1,
    spellDamage: "",
    cooldown: 120,
    cooldownTimer: 0,
    onCooldown: false,
    toolTipDescription1: "+100% damage dealt for 10 seconds.",
    toolTipDescription2: "",
    toolTipDescription3: "",
  },
  {
    spellName: "NoClick",
    src: "./Images/Spells/edited-7.png",
    alt: "aaa",
    index: 6,
    spellUnlocked: true,
    levelToUnlock: 1,
    spellDamage: "",
    cooldown: 0,
    cooldownTimer: 0,
    onCooldown: false,
    toolTipDescription1: "Passively gain an extra 5% gold from kills",
    toolTipDescription2: "",
    toolTipDescription3: "",
  },
];
