export const spellData = [
  {
    spellName: "Spell 1",
    src: "./Images/Spells/Spell1.png",
    alt: "aaa",
    index: 0,
    spellUnlocked: true,
    levelToUnlock: 1,
    spellDamage: 0,
    cooldown: 60,
    cooldownTimer: 0,
    onCooldown: false,
    toolTipDescription1: "Deal ",
    toolTipDescription2:
      " damage Instantly. Damage Scales with level and experience.",
    toolTipDescription3: "Kills with this spell grant +20% gold.",
    activeTime: 0,
    active: false,
  },
  {
    spellName: "Spell 2",
    src: "./Images/Spells/Spell2.png",
    alt: "aaa",
    index: 1,
    spellUnlocked: true,
    levelToUnlock: 1,
    spellDamage: "",
    cooldown: 120,
    cooldownTimer: 0,
    onCooldown: false,
    toolTipDescription1: "+100% Nutrient gathering for 10 seconds.",
    toolTipDescription2: "",
    toolTipDescription3: "",
    activeTime: 0,
    active: false,
  },
  {
    spellName: "Spell 3",
    src: "./Images/Spells/Spell3.png",
    alt: "aaa",
    index: 2,
    spellUnlocked: false,
    levelToUnlock: 2,
    spellDamage: "",
    cooldown: 120,
    cooldownTimer: 0,
    onCooldown: false,
    toolTipDescription1: "5x Nutrients per click for 7 seconds.",
    toolTipDescription2: "",
    toolTipDescription3: "",
    activeTime: 0,
    active: false,
  },
  {
    spellName: "Spell 4",
    src: "./Images/Spells/Spell4.png",
    alt: "aaa",
    index: 3,
    spellUnlocked: false,
    levelToUnlock: 2,
    spellDamage: 111,
    cooldown: 180,
    cooldownTimer: 0,
    onCooldown: false,
    toolTipDescription1: "Increase your current Colonies by 10% ",
    toolTipDescription2: "",
    toolTipDescription3: "",
    activeTime: 0,
    active: false,
  },
  {
    spellName: "Spell 5",
    src: "./Images/Spells/Spell5.png",
    alt: "aaa",
    index: 4,
    spellUnlocked: false,
    levelToUnlock: 3,
    spellDamage: "",
    cooldown: 300,
    cooldownTimer: 0,
    onCooldown: false,
    toolTipDescription1: "Reset Cooldowns of all spells.",
    toolTipDescription2: "",
    toolTipDescription3: "",
    activeTime: 0,
    active: false,
  },
  {
    spellName: "Spell 6",
    src: "./Images/Spells/Spell6.png",
    alt: "aaa",
    index: 5,
    spellUnlocked: false,
    levelToUnlock: 3,
    spellDamage: "",
    cooldown: 120,
    cooldownTimer: 0,
    onCooldown: false,
    toolTipDescription1: "+100% damage dealt for 10 seconds.",
    toolTipDescription2: "",
    toolTipDescription3: "",
    activeTime: 0,
    active: false,
  },
  {
    spellName: "NoClick",
    src: "./Images/Spells/Spell7.png",
    alt: "aaa",
    index: 6,
    spellUnlocked: false,
    levelToUnlock: 4,
    spellDamage: "",
    cooldown: 0,
    cooldownTimer: 0,
    onCooldown: false,
    toolTipDescription1: "Passively gain an extra 5% gold from kills",
    toolTipDescription2: "",
    toolTipDescription3: "",
    activeTime: 0,
    active: false,
  },
];
