export const spellData = [
  {
    spellName: "Smite",
    src: "./Images/Spells/edited-1.png",
    alt: "aaa",
    index: 0,
    spellUnlocked: true,
    levelToUnlock: 1,
  },
  {
    spellName: "Smite",
    src: "./Images/Spells/edited-2.png",
    alt: "aaa",
    index: 1,
    spellUnlocked: true,
    levelToUnlock: 1,
  },
  {
    spellName: "Smite",
    src: "./Images/Spells/edited-3.png",
    alt: "aaa",
    index: 2,
    spellUnlocked: true,
    levelToUnlock: 1,
  },
  {
    spellName: "Smite",
    src: "./Images/Spells/edited-4.png",
    alt: "aaa",
    index: 3,
    spellUnlocked: true,
    levelToUnlock: 1,
  },
  {
    spellName: "Smite",
    src: "./Images/Spells/edited-5.png",
    alt: "aaa",
    index: 4,
    spellUnlocked: false,
    levelToUnlock: 2,
  },
  {
    spellName: "Smite",
    src: "./Images/Spells/edited-6.png",
    alt: "aaa",
    index: 5,
    spellUnlocked: false,
    levelToUnlock: 3,
  },
  {
    spellName: "Smite",
    src: "./Images/Spells/edited-7.png",
    alt: "aaa",
    index: 6,
    spellUnlocked: false,
    levelToUnlock: 3,
  },
];
