export const gameData = [
  {
    goldPerKill: 30,
    xpPerKill: 75,
    maxHpPerKill: 200,
    hpIncreasePerKill: 4,
    xpToLevelUp: 1000,
    id: 1,
    spreadButtonImage: "./Images/Locations/Continent-Africa.webp",
    spreadButtonName: "Africa",
  },
  {
    goldPerKill: 120,
    xpPerKill: 125,
    maxHpPerKill: 1185,
    hpIncreasePerKill: 24,
    xpToLevelUp: 2000,
    id: 2,
    spreadButtonImage: "./Images/Locations/Continent-Australia.webp",
    spreadButtonName: "Australia",
  },
  {
    goldPerKill: 530,
    xpPerKill: 250,
    maxHpPerKill: 7450,
    hpIncreasePerKill: 149,
    xpToLevelUp: 3500,
    id: 3,
    spreadButtonImage: "./Images/Locations/Continent-Europe.webp",
    spreadButtonName: "Europe",
  },
  {
    goldPerKill: 2540,
    xpPerKill: 400,
    maxHpPerKill: 47875,
    hpIncreasePerKill: 957,
    xpToLevelUp: 7000,
    id: 4,
    spreadButtonImage: "./Images/Locations/Continent-Asia.webp",
    spreadButtonName: "Asia",
  },
  {
    goldPerKill: 12550,
    xpPerKill: 550,
    maxHpPerKill: 307500,
    hpIncreasePerKill: 6150,
    xpToLevelUp: 10000,
    id: 5,
    spreadButtonImage: "./Images/Locations/Continent-SouthAmerica.png",
    spreadButtonName: "South America",
  },
  {
    goldPerKill: 50920,
    xpPerKill: 700,
    maxHpPerKill: 1000000, //UNKNOWN
    hpIncreasePerKill: 19980,
    xpToLevelUp: 15000,
    id: 6,
    spreadButtonImage: "./Images/Locations/Continent-NorthAmerica.png",
    spreadButtonName: "North America",
  },
  {
    goldPerKill: 100000,
    xpPerKill: 900, //UNKNOWN
    maxHpPerKill: 10000000,
    hpIncreasePerKill: 90211,
    xpToLevelUp: 25000,
    id: 7,
    spreadButtonImage: "./Images/Locations/Continent-America.png",
    spreadButtonName: "The Americas",
  },
  {
    goldPerKill: 100000,
    xpPerKill: 1000, //UNKNOWN
    maxHpPerKill: 10000000,
    hpIncreasePerKill: 100000,
    xpToLevelUp: 9999999999,
    id: 8,
    spreadButtonImage: "./Images/Locations/Continent-America.png",
    spreadButtonName: "The Americas",
  },
];
