export const gameData = [
  {
    goldPerKill: 30,
    xpPerKill: 75,
    maxHpPerKill: 200,
    hpIncreasePerKill: 4,
    xpToLevelUp: 1000,
    id: 1,
    spreadButtonImage: "./Images/Locations/Continent-Africa.webp",
    spreadButtonName: "Africa",
  },
  {
    goldPerKill: 120,
    xpPerKill: 345,
    maxHpPerKill: 1185,
    hpIncreasePerKill: 24,
    xpToLevelUp: 6250,
    id: 2,
    spreadButtonImage: "./Images/Locations/Continent-Australia.webp",
    spreadButtonName: "Australia",
  },
  {
    goldPerKill: 530,
    xpPerKill: 1655,
    maxHpPerKill: 7450,
    hpIncreasePerKill: 149,
    xpToLevelUp: 31250,
    id: 3,
    spreadButtonImage: "./Images/Locations/Continent-Europe.webp",
    spreadButtonName: "Europe",
  },
  {
    goldPerKill: 2540,
    xpPerKill: 8165,
    maxHpPerKill: 47875,
    hpIncreasePerKill: 957,
    xpToLevelUp: 156250,
    id: 4,
    spreadButtonImage: "./Images/Locations/Continent-Asia.webp",
    spreadButtonName: "Asia",
  },
  {
    goldPerKill: 12550,
    xpPerKill: 40675,
    maxHpPerKill: 307500,
    hpIncreasePerKill: 6150,
    xpToLevelUp: 781250,
    id: 5,
    spreadButtonImage: "./Images/Locations/Continent-SouthAmerica.png",
    spreadButtonName: "South America",
  },
  {
    goldPerKill: 62560,
    xpPerKill: 203185,
    maxHpPerKill: 1950000,
    hpIncreasePerKill: 50000,
    xpToLevelUp: 3900000,
    id: 6,
    spreadButtonImage: "./Images/Locations/Continent-NorthAmerica.png",
    spreadButtonName: "North America",
  },
  {
    goldPerKill: 312570,
    xpPerKill: 1000000,
    maxHpPerKill: 12000000,
    hpIncreasePerKill: 250000,
    xpToLevelUp: 19530000,
    id: 7,
    spreadButtonImage: "./Images/Locations/Continent-America.png",
    spreadButtonName: "The Americas",
  },
  {
    goldPerKill: 312570,
    xpPerKill: 1000000,
    maxHpPerKill: 12000000,
    hpIncreasePerKill: 250000,
    xpToLevelUp: 1e50, //Not meant to level up past this point
    id: 8,
    spreadButtonImage: "./Images/Locations/Continent-America.png",
    spreadButtonName: "The Americas",
  },
];
